EQUITY="EQUITY"
DEBT="DEBT"
ELSS="ELSS"

mf_types = {
  "TATA DIGITAL INDIA FUND - DIRECT PLAN": EQUITY,
  "AXIS LONG TERM EQUITY FUND - DIRECT PLAN":ELSS,
  "Aditya Birla Sun Life Tax Relief 96 - Direct Plan":ELSS,
  "IDFC Tax Advantage (ELSS) Fund - Direct Plan":ELSS,
  "Lu0026T Tax Advantage Fund - Direct Plan":ELSS,
  "NIPPON INDIA SMALL CAP FUND - DIRECT PLAN":EQUITY,
  "KOTAK BOND SHORT TERM FUND - DIRECT PLAN":DEBT,
  "AXIS LIQUID FUND - DIRECT PLAN":DEBT,
  "FRANKLIN INDIA LIQUID FUND - DIRECT PLAN":DEBT,
  "SBI MAGNUM CONSTANT MATURITY FUND - DIRECT PLAN":DEBT,
  "MOTILAL OSWAL NIFTY BANK INDEX FUND - DIRECT PLAN":EQUITY,
  "AXIS FOCUSED 25 FUND - DIRECT PLAN":EQUITY,
  "MIRAE ASSET GREAT CONSUMER FUND - DIRECT PLAN":EQUITY,
  "HDFC LIQUID FUND - DIRECT PLAN": DEBT,
  "Reliance Small Cap Fund - Direct Plan": EQUITY,
  "PARAG PARIKH FLEXI CAP FUND - DIRECT PLAN": EQUITY,
  "TATA BALANCED ADVANTAGE FUND - DIRECT PLAN": EQUITY,
  "HSBC ELSS FUND - DIRECT PLAN": ELSS
}
